name: testing
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'


jobs:
  build:
     name: 'foo'
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: ls
       run: |
         ls -al
